<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?=$systemConfig['host']?>">首页</a></li>
        <?php if (isset($crumbs) && !empty($crumbs) && is_array($crumbs)):foreach ($crumbs as $val):?>
            <li class="breadcrumb-item"><a <?=isset($val['url']) && !empty($val['url']) ? "href='{$val['url']}'" : ''?>><?=$val['name']?></a></li>
        <?php endforeach;endif;?>
        <li class="breadcrumb-item active" aria-current="page"><?=$title?></li>
    </ol>
</nav>
<div class="row">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-12" id="list">
                <ul class="list-unstyled">
                    <?php if (!empty($articles)):foreach ($articles as $val):?>
                        <li >
                            <div class="media">
                                <?php if(!empty($val['img_url'])):?><img src="<?=$val['img_url']?>" class="mr-3" alt="<?=$val['title']?>" width="160"><?php endif;?>
                                <div class="media-body">
                                    <h5 class="mt-0 mb-1"><a href="/article/index.html?id=<?=$val['id']?>"><?=$val['title']?></a></h5>
                                    <?=$val['desc']?>
                                </div>
                            </div>
                            <div class="info">
                                <?php if (!empty($val['tags'])):?>
                                <span class="tag"><a href="javascript:;" title="<?=$val['tags']?>"><?=$val['tags']?></a></span>
                                <?php endif;?>
                                <span class="dtime"><?=substr($val['create_at'], 0, 10)?></span>
                                <span class="viewnum">浏览（<?=$val['clicks']?>）</span>
                                <span class="read"><a href="/article/index.html?id=<?=$val['id']?>" class="green">阅读原文</a></span>
                            </div>
                        </li>
                    <?php endforeach;endif;?>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="row">
            <div class="col-md-12 right-click-list">
                <ul class="list-unstyled">
                    <?php if (!empty($clickArticles)):foreach ($clickArticles as $val):?>
                    <li class="media">
                        <?php if(!empty($val['img_url'])):?><img src="<?=$val['img_url']?>" class="mr-3" alt="<?=$val['title']?>" width="80"><?php endif;?>
                        <div class="media-body">
                            <h5 class="mt-0 mb-1"><a href="/article/index.html?id=<?=$val['id']?>"><?=$val['title']?></a></h5>
                            <?=$val['desc']?>
                        </div>
                    </li>
                    <?php endforeach;endif;?>
                </ul>
            </div>
        </div>
    </div>
</div>