<article>
    <h1 class="t_nav"><span>您现在的位置是：首页 > 文章列表</span></h1>
    <div class="blogs">
        <div class="mt20"></div>
        <?php if (!empty($articles)):foreach ($articles as $val):?>
        <li> <span class="blogpic"><a href="/index/index/info.html?id=<?=$val['id']?>"><?php if (!empty($val['img_url']))echo '<img src="'.$val['img_url'].'">';?></a></span>
            <h3 class="blogtitle"><a href="/index/index/info.html?id=<?=$val['id']?>"><?=$val['title']?></a></h3>
            <div class="bloginfo">
                <p><?=$val['desc']?></p>
            </div>
            <div class="autor"><span class="lm"><a href="javascript:;" title="<?=$val['tags']?>" class="classname"><?=$val['tags']?></a></span><span class="dtime"><?=\woodlsy\phalcon\library\Helper::now('Y-m-d', strtotime($val['create_at']))?></span><span class="viewnum">浏览（<?=$val['clicks']?>）</span><span class="readmore"><a href="/index/index/info.html?id=<?=$val['id']?>">阅读原文</a></span></div>
        </li>
        <?php endforeach;endif;?>
        <div class="pagelist">
            <a title="总条数">&nbsp;<b><?=$articleCount?></b> </a>&nbsp;&nbsp;&nbsp;<b class="hidden">1</b>&nbsp;
        </div>
    </div>
    <div class="sidebar">
        <div class="search">
            <form action="/index/index/search.html" method="get" name="searchform" id="searchform">
                <input name="keyword" id="keyword" class="input_text" value="请输入关键字" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字'}" type="text">
                <button class="input_submit" type="submit">搜索</button>
            </form>
        </div>
<!--        <div class="lmnav">-->
<!--            <h2 class="hometitle">栏目导航</h2>-->
<!--            <ul class="navbor">-->
<!--                <li><a href="#">关于我</a></li>-->
<!--                <li><a href="share.html">模板分享</a>-->
<!--                    <ul>-->
<!--                        <li><a href="list.html">个人博客模板</a></li>-->
<!--                    </ul>-->
<!--                </li>-->
<!--                <li><a href="list.html">学无止境</a>-->
<!--                    <ul>-->
<!--                        <li><a href="#">HTML5+CSS3</a></li>-->
<!--                    </ul>-->
<!--                </li>-->
<!--                <li><a href="#">慢生活</a></li>-->
<!--            </ul>-->
<!--        </div>-->
        <div class="paihang">
            <h2 class="hometitle">点击排行</h2>
            <ul>
                <?php if (!empty($clickArticles)):foreach ($clickArticles as $val):?>
                    <li><b><a href="/index/article/info.html?id=<?=$val['id']?>" target="_blank"><?=$val['title']?></a></b>
                        <p><i><?php if (!empty($val['img_url']))echo '<img src="'.$val['img_url'].'">';?></i><?=$val['desc']?></p>
                    </li>
                <?php endforeach;endif;?>
            </ul>
        </div>
        <!--        <div class="cloud">-->
        <!--            <h2 class="hometitle">标签云</h2>-->
        <!--            <ul>-->
        <!--                <a href="/">MYSQL</a>-->
        <!--            </ul>-->
        <!--        </div>-->
    </div>
</article>