<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?=$title?></h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="post" enctype="multipart/form-data" action="/yadmin/article/setArticle.html">
                <input type="hidden" name="id" value="<?=$data['id'] ?? 0?>">
                <div class="box-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">文章标题</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="title" name="title" value="<?=$data['title'] ?? ''?>" placeholder="文章标题">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">文章分类</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="category_id">
                                <?php if (!empty($category)):foreach ($category as $key => $val):?>
                                <option value="<?=$key?>" <?php if (isset($data['category_id']) && $data['category_id'] == $key)echo 'selected'?>><?=$val?></option>
                                <?php endforeach;endif;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">缩略图</label>
                        <div class="col-sm-10">
                            <input type="file" name="file" id="exampleInputFile">
                            <p class="help-block">建议尺寸 240 * 160</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">文章内容</label>
                        <div class="col-sm-10">
                            <textarea id="editor1" name="content" rows="10" cols="80">
                                                    <?=htmlspecialchars_decode($data['content']) ?? ''?>
                            </textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">标签</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="tags" name="tags" value="<?=$data['tags'] ?? ''?>" placeholder="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">排序</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="sort" name="sort" value="<?=$data['sort'] ?? '50'?>" placeholder="排序">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">发布</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="is_push" id="is_push1" value="0" <?php if (!isset($data['is_deleted']) || $data['is_deleted'] == 1)echo 'checked'?>>
                                        是
                                    </label>
                                    <label>
                                        <input type="radio" name="is_push" id="is_push2" value="1" <?php if (isset($data['is_deleted']) && (int)$data['is_deleted'] === 0)echo 'checked'?>>
                                        否
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary btnSubmit">保存</button>
                </div>
            </form>
        </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
<!-- CK Editor -->
<!--<script src="https://cdn.ckeditor.com/4.13.0/full/ckeditor.js"></script>-->
<script src="/dist/plugins/ckeditor/ckeditor.js"></script>
  <script>
    $(function () {
      $('.btnSubmit').click(function(){
        if($('#title').val() == '') {
            alertMsg('error', '标题不能为空');
            return false;
        }
      });
        // CKEDITOR.plugins.addExternal('codesnippet','/plugins/codesnippet/');
        CKEDITOR.replace('editor1',{extraPlugins:'codesnippet'});
        <?php if (isset($alertError) && !empty($alertError)):?>
        alertMsg('error', '<?=$alertError?>');
        <?php endif;?>
    })
  </script>