<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?=$title?></h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="post">
                <input type="hidden" name="id" value="<?=$data['id'] ?? 0?>">
                <div class="box-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">分类名称</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="name" name="name" value="<?=$data['name'] ?? ''?>" placeholder="分类名称">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">上级分类</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="pid">
                                <option value="0">顶级分类</option>
                                <?php if (!empty($category)):foreach ($category as $key => $val):?>
                                <option value="<?=$key?>" <?php if (isset($data['pid']) && $data['pid'] == $key)echo 'selected'?>><?=$val?></option>
                                <?php endforeach;endif;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">状态</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="is_deleted" id="optionsRadios1" value="0" <?php if (!isset($data['is_deleted']) || $data['is_deleted'] != 1)echo 'checked'?>>
                                        正常
                                    </label>
                                    <label>
                                        <input type="radio" name="is_deleted" id="optionsRadios2" value="1" <?php if (isset($data['is_deleted']) && $data['is_deleted'] == 1)echo 'checked'?>>
                                        删除
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary btnSubmit">保存</button>
                </div>
            </form>
        </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
  <script>
    $(function () {
      $('.btnSubmit').click(function(){
        if($('#name').val() == '') {
            alertMsg('error', '分类名称不能为空');
            return false;
        }
      });
        <?php if (isset($alertError) && !empty($alertError)):?>
        alertMsg('error', '<?=$alertError?>');
        <?php endif;?>
    })
  </script>